services:  
  # Cloud service - handles its own SDK building
  cloud:
    stop_grace_period: 10s
    init: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8003:80"
    environment:
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: bash -c "bun install && cd packages/sdk && bun run build && cd ../cloud && bun install && bun run dev"
    tty: true
    stdin_open: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7.0
    restart: always  # 自动重启
    volumes:
      - mongodb_data:/data/db  # 数据持久化卷
    # 可选：限制资源使用
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  node_modules:
  bun_cache:
  mongodb_data:
